version: '3'

services:

  frontend:
    build: frontend
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    depends_on:
      - db
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  db:
    image: mariadb
    volumes:
        - dbdata:/var/lib/mysql
#        - ./init_db:/docker-entrypoint-initdb.d
#    volumes_from:
#      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=420870_nam
      - MYSQL_USER=420870_nam
      - MYSQL_PASSWORD=Q1w2e3r4
#      - MARIADB_USER=420870_nam
#      - MARIADB_PASS=Q1w2e3r

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    #restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db


  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret

volumes:
    dbdata:
